### ISSUE TITLE
Invalid JSON returned when searching for events by keyword

### ISSUE THREAD

**Issue by ColmanOB** [ColmanOB/SessionBuddy#1]
There appears to be a bug in the JSON returned by the API at [https://thesession.org](url) when searching for events by keyword.  

As far as I can tell, with my limited knowledge of JSON formatting, there are stray commas where they are not expected.  

Specifically, these appear after the `"name"` value in both the `area` and `country` objects.  See the commas highlighted in yellow in the attached image.

To replicate the issue:

1. Do a search for events using "london" as the search term: 
`https://thesession.org/events/search?q=london&format=json`
2. Paste the resulting JSON into a validator such as this one: [http://jsonlint.com](url)
3. This should highlight the problematic lines

![image](https://cloud.githubusercontent.com/assets/14179195/22529492/84b98a1e-e8cf-11e6-83fe-a7c411c13689.png)

**Comment by adactio** [comment]
I've removed those stray commas now—thanks for catching that.

**Comment by ColmanOB** [comment]
Thanks Jeremy, that was quick!  The events search now works as expected for me.
